({'name': 'flask.app', 'msg': 'Microblog startup', 'args': (), 'levelname': 'INFO', 'levelno': 20, 'pathname': '/Users/saurabhbansal/projectblog/app/__init__.py', 'filename': '__init__.py', 'module': '__init__', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 49, 'funcName': '<module>', 'created': 1548883318.949056, 'msecs': 949.0559101104736, 'relativeCreated': 405.2448272705078, 'thread': 4589036992, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 45254, 'message': 'Microblog startup', 'asctime': '2019-01-30 15:21:58,949'}sctime)s INFO: Microblog startup [in /Users/saurabhbansal/projectblog/app/__init__.py:49]
({'name': 'flask.app', 'msg': 'Exception on /login [GET]', 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': '/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py', 'filename': 'app.py', 'module': 'app', 'exc_info': (<class 'werkzeug.routing.BuildError'>, BuildError('reset_password_request', {}, None), <traceback object at 0x10ca33288>), 'exc_text': 'Traceback (most recent call last):\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise\n    raise value\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/Users/saurabhbansal/projectblog/app/routes.py", line 67, in login\n    return render_template("login.html", title = "Sign in" , form=form)\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template\n    context, ctx.app)\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render\n    rv = template.render(context)\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render\n    return original_render(self, *args, **kwargs)\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render\n    return self.environment.handle_exception(exc_info, True)\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise\n    raise value.with_traceback(tb)\n  File "/Users/saurabhbansal/projectblog/app/templates/login.html", line 1, in top-level template code\n    {%extends "base.html" %}\n  File "/Users/saurabhbansal/projectblog/app/templates/base.html", line 29, in top-level template code\n    {% block content %}{% endblock %}\n  File "/Users/saurabhbansal/projectblog/app/templates/login.html", line 25, in block "content"\n    <a href = "{{url_for(\'reset_password_request\')}}">Click to Reset It</a>\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for\n    return appctx.app.handle_url_build_error(error, endpoint, values)\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error\n    reraise(exc_type, exc_value, tb)\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise\n    raise value\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for\n    force_external=external)\n  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build\n    raise BuildError(endpoint, values, method, self)\nwerkzeug.routing.BuildError: Could not build url for endpoint \'reset_password_request\'. Did you mean \'reset_password_user\' instead?', 'stack_info': None, 'lineno': 1761, 'funcName': 'log_exception', 'created': 1548883331.238404, 'msecs': 238.4040355682373, 'relativeCreated': 12694.592952728271, 'thread': 123145469300736, 'threadName': 'Thread-2', 'processName': 'MainProcess', 'process': 45254, 'message': 'Exception on /login [GET]', 'asctime': '2019-01-30 15:22:11,238'}sctime)s ERROR: Exception on /login [GET] [in /Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/saurabhbansal/projectblog/app/routes.py", line 67, in login
    return render_template("login.html", title = "Sign in" , form=form)
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/saurabhbansal/projectblog/app/templates/login.html", line 1, in top-level template code
    {%extends "base.html" %}
  File "/Users/saurabhbansal/projectblog/app/templates/base.html", line 29, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/saurabhbansal/projectblog/app/templates/login.html", line 25, in block "content"
    <a href = "{{url_for('reset_password_request')}}">Click to Reset It</a>
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/saurabhbansal/projectblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'reset_password_user' instead?
